artifact_uri: /Users/ganesh/Desktop/Git-kyndryl/CAPSTONE-PROJECT/capstone-sim-shelf-space/simcard-shelf-space-2/runs/mlflow/662197954743695805/215b558fddfe4dd8b960ddad171271b2/artifacts
end_time: 1729204097126
entry_point_name: ''
experiment_id: '662197954743695805'
lifecycle_stage: active
run_id: 215b558fddfe4dd8b960ddad171271b2
run_name: train4
run_uuid: 215b558fddfe4dd8b960ddad171271b2
source_name: ''
source_type: 4
source_version: ''
start_time: 1729173984562
status: 3
tags: []
user_id: ganesh
