artifact_location: /Users/ganesh/Desktop/Git-kyndryl/CAPSTONE-PROJECT/capstone-sim-shelf-space/simcard-shelf-space-2/runs/mlflow/0
creation_time: 1728927983278
experiment_id: '0'
last_update_time: 1728927983278
lifecycle_stage: active
name: Default
